// <auto-generated />
using CoreBuildApi.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreBuildApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327020616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreBuildApi.models.Cpu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CacheL3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrecuenciaBase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrecuenciaTurbo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Generacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GraficosIntegrados")
                        .HasColumnType("text");

                    b.Property<int>("Hilos")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Nucleos")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoporteRam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TdpWatts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cpus");
                });

            modelBuilder.Entity("CoreBuildApi.models.Gpu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusMemoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConectoresEnergia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConsumoWatts")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrecuenciaBase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrecuenciaBoost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuenteRecomendada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoVram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionPcie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gpus");
                });

            modelBuilder.Entity("CoreBuildApi.models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Almacenamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompatibilidadCpu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conectividad")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Puertos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlotsRam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoRam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VelocidadRamMax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("CoreBuildApi.models.Psu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Certificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conectores")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eficiencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PotenciaWatts")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Protecciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoModular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ventilador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Psus");
                });

            modelBuilder.Entity("CoreBuildApi.models.Ram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CapacidadTotal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Configuracion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Latencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Velocidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Voltaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rams");
                });
#pragma warning restore 612, 618
        }
    }
}
